### ISSUE TITLE
boj random 커맨드 입력 시 에러가 발생합니다.

### ISSUE THREAD

**Issue by 0Chan-smc** [zshchun/bojtools#1]
`boj random s s` 입력 시 아래와 같은 에러가 발생합니다.
```
[+] Random pick s5..s1
Traceback (most recent call last):
  File "/home/smc/.local/bin/boj", line 8, in <module>
    sys.exit(main())
  File "/home/smc/.local/lib/python3.10/site-packages/baekjoon/__main__.py", line 58, in main
    args.func(args)
  File "/home/smc/.local/lib/python3.10/site-packages/baekjoon/solved.py", line 41, in pick_random
    asyncio.run(async_query_solvedac(url, args.list))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/smc/.local/lib/python3.10/site-packages/baekjoon/solved.py", line 93, in async_query_solvedac
    save_solved_list(tr[1:])
  File "/home/smc/.local/lib/python3.10/site-packages/baekjoon/solved.py", line 61, in save_solved_list
    prob = extract_problem(t)
  File "/home/smc/.local/lib/python3.10/site-packages/baekjoon/solved.py", line 16, in extract_problem
    prob['pid'] = int(td[0].xpath('.//span[not(@class)]')[0].text)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

그리고 혹시 `config.toml`에 solved_token에 어떤 걸 넣어야 하는지 알 수 있을까요?

**Comment by zshchun** [comment]
답변이 늦어서 죄송합니다.

pypi에 최신 버전이 안올라가 있었습니다.

최신으로 갱신했습니다.

다음 CLI로 업데이트 버전으로 설치 됩니다.

```
pip3 install -U bojtools
```

boj_token에는 백준 cookie를, solved_token에는 solved.ac 의 cookie를 입력하시면 됩니다.

reCAPTCHA 때문에 자동 로그인은 지원하지 않고 있습니다.
